### PR TITLE
Add C++ wrappers for libcanard

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@bugobliterator feel free to merge when ready for the main ArduPilot PR

**Comment by davidbuzz** [comment]
i found i had to install these when trying this code, might want to add them as dev pre-requisites..?
sudo apt-get install gcc-multilib g++-multilib catch2

i also found that test don't build in a 64bit system with glibc > 2.33 as  SIGSTKSZ is no longer defined the way it used to be... I search/replaced SIGSTKSZ to 32768 and that "fixed it for me"..
    
 [  7%] Building CXX object CMakeFiles/run_tests.dir/catch/test_main.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/buzz/libcanard/tests/catch/catch.hpp:6456,
                 from /home/buzz/libcanard/tests/catch/test_main.cpp:28:
/home/buzz/libcanard/tests/catch/catch.hpp:6631:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 6631 |     char FatalConditionHandler::altStackMem[SIGSTKSZ] = {};
      |                                             ^~~~~~~~
make[2]: *** [CMakeFiles/run_tests.dir/build.make:76: CMakeFiles/run_tests.dir/catch/test_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/run_tests.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
